### ISSUE TITLE
New bug fix affects ghcjs in-tree copy of JMacro

### ISSUE THREAD

**Issue by ddssff** [ghcjs/ghcjs#354]
Here is a link to an important JMacro fix:

http://hub.darcs.net/gershomb/jmacro/patch/20150527173150-4a8a9

**Comment by luite** [comment]
ok, I recall this being a change for for loops with labeled breaks not working as they should (I reported that).

I'll pull in this change, but that does mean other things break. At the time I was doing some experiments with optimizing certain constructs, which did use labeled breaks, but I don't think anything uses this at the moment. The new codegen uses its own IR rather than JMacro, so this is a temporary issue.

**Comment by luite** [comment]
On second thought, I think I never pulled in the buggy commit in the first place, this is the relevant code, isn't it?

https://github.com/ghcjs/ghcjs/blob/a73f65a9d9d8639cd23707edc4fdc06fb77c092d/src/Compiler/JMacro/QQ.hs#L508-L509

**Comment by luite** [comment]
reopen if i did inadvertently add the buggy code

**Comment by ddssff** [comment]
That looks right.
