### ISSUE TITLE
ghcjs-boot fails on SUSE Linux due to character encoding

### ISSUE THREAD

**Issue by cdsmith** [ghcjs/ghcjs#367]
When installing GHCJS on SUSE Linux, booting fails.  The error message is:

```
[long path]/cabal/Cabal/dist/setup/setup.jsexe/all.js: hGetContents: invalid argument (invalid byte sequence)
```

It looks like the problem section of the file is (viewed with less):

```
} else if (global.MessageChannel) {
    // For web workers, where supported
    installMessageChannelImplementation();
} else if (doc && "onreadystatechange" in doc.createElement("script")) {
    // For IE 6<E2><80><93>8
    installReadyStateChangeImplementation();
} else {
    // For older browsers
    installSetTimeoutImplementation();
}
```

which appears to be copied from https://github.com/YuzuJS/setImmediate/blob/master/setImmediate.js  Note that the dash in the comment is some unicode character, not an ASCII dash.

**Comment by luite** [comment]
Is it really GHCJS that gives this error and not the `all.js` file itself? If it's GHCJS then it looks like this happens because GHCJS uses `text` functions to read the `all.js` file when generating the executable script (adding the `#!/path/to/node` line). I think it should use `bytestring` instead.

Still it might be better to replace the offending character in the shims repository too.

**Comment by luite** [comment]
fixed in `improved-base` branch

**Comment by cdsmith** [comment]
If you don't intend to fix this in the master branch, feel free to close this. I've moved CodeWorld to GHC 7.10.2 and the improved-base branch, so master is no longer is of any importance to me. Thanks!

**Comment by jberryman** [comment]
`improved-base` doesn't seem to be a branch anymore so I suspect this can be closed
