### ISSUE TITLE
Could GHCJS be a GHC backend? Or is it?

### ISSUE THREAD

**Issue by danse** [ghcjs/ghcjs#425]
Sometimes working with GHCJS i have the feeling that some parts of GHC are duplicated here. Issues like #379 and #166 seem to show that some part of GHC's code has been copied from or needs to be kept aligned with code from GHC. I am ignorant about GHC's internals, but i though that asking a question about the integration model could be useful also for others in the future to better understand the design and follow the idea. I guess that GHC's support for custom backends is not flexible enough, anyway i did not find any issue or any documentation about this so i thought that asking the question here would not hurt

**Comment by luite** [comment]
GHC hasn't really been designed as a library, other than the relatively high level `GHC` module, which is far too limited to build GHCJS on; it just exposes all internals through the `ghc` package.

Unfortunately because of this, GHCJS has had to copy code from GHC several times, because we needed some changes from GHC's behaviour, which calling into the library didn't allow. This has been followed up by sending a patch upstream to GHC to make the API more flexible a few times now. It's still a bit of a maintenance issue, with major breakage every GHC version.

Given the current state of things, it's probably easier to merge GHCJS upstream than to redesign the GHC API to make a clean pluggable back end possible. But at the moment there is still a bit too much changing in GHCJS, keeping it separate makes it easier to change things here. So we deal with the additional maintenance, for now...

**Comment by danse** [comment]
Cool, i thought that the way of backends was not taken by design, in order to improve readability or something similar. Maybe one day, together with `-fasm` and `-fllvm`, GHC will have a `-fasmjs`! I see that there is even a `-fbyte-code`, i wonder if it compiles to to the Java virtual machine. Anyway thanks for taking the time to elaborate on this!

**Comment by luite** [comment]
That is `GHCi` bytecode, also used by Template Haskell, basically interpreted STG.
