### ISSUE TITLE
Ubuntu 14.04 cabal: Could not resolve dependencies

### ISSUE THREAD

**Issue by UrKr** [ghcjs/ghcjs#469]
When I do run  cabal install inside the cloned repository, I get the following error:

```
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: ghcjs-0.2.0 (user goal)
trying: transformers-compat-0.5.1.4/installed-1b4... (dependency of
ghcjs-0.2.0)
next goal: optparse-applicative (dependency of ghcjs-0.2.0)
rejecting: optparse-applicative-0.12.1.0/installed-378..., 0.12.1.0, 0.12.0.0
(conflict: ghcjs => optparse-applicative>=0.11 && <0.12)
rejecting: optparse-applicative-0.11.0.2, 0.11.0.1, 0.11.0 (conflict:
transformers-compat => transformers==0.5.2.0/installed-43a...,
optparse-applicative => transformers>=0.2 && <0.5)
rejecting: optparse-applicative-0.10.0, 0.9.1.1, 0.9.1, 0.9.0, 0.8.1, 0.8.0.1,
0.8.0, 0.7.0.2, 0.7.0.1, 0.7.0, 0.6.0, 0.5.2.1, 0.5.2, 0.5.1, 0.5.0, 0.4.3,
0.4.2, 0.4.1, 0.4.0, 0.3.2, 0.3.1, 0.3.0, 0.2.0, 0.1.1, 0.1.0, 0.0.1
(conflict: ghcjs => optparse-applicative>=0.11 && <0.12)
Dependency tree exhaustively searched.

```

**Comment by mgsloan** [comment]
The issue is that cabal-install wants to find a build plan that's compatible with the packages that are already in your package database.  This generally makes cabal-install unreliable and difficult for people to use without knowing some newer workflows.  One of these newer workflows is using cabal sandboxes.

If you just want to use GHCJS, then the approach I recommend is http://docs.haskellstack.org/en/stable/ghcjs/ .  I've gotten lots of feedback that this has been the most streamlined way for people to get a working ghcjs setup.  If you want to build and install ghcjs, similarly, `stack install` is the way to go.

**Comment by UrKr** [comment]
Thanks for the reply - that worked!

**Comment by mgsloan** [comment]
Great!

**Comment by felipecsl** [comment]
Using Stack was the only way that worked for me. Using the README instructions didn't work at all (on OSX). Might want to make this information more prominent so that other newcomers (like me) don't struggle as well.

**Comment by dud3** [comment]
Nope, followed readme, it just doesn't work for me.

**Comment by dud3** [comment]
I got the following:
```
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: ghcjs-0.2.0
trying: base-4.6.0.1/installed-8aa...
trying: haddock-api-2.17.3
rejecting: ghc-boot-8.0.2, 8.0.1 (conflict: base==4.6.0.1/installed-8aa...,
ghc-boot => base>=4.7 && <4.10)
```
