### ISSUE TITLE
REPL is unstable and slow

### ISSUE THREAD

**Issue by artemyarulin** [ghcjs/ghcjs#483]
Hi,

May I ask couple of questions about REPL implementation in ghcjs. I'm very new to Haskell and ghcjs in particular, so I apologise if my questions would be stupid:

- REPL is unstable. Restarting browsers/server breaks the whole thing. Not sure why, looks like client reconnects just fine, is it server which breaks? Maybe you can point me what may cause it?
- REPL is slow. In certain cases it works fine, like evaluating `2` works OK. But it takes around **30** seconds on my machine to evaluate `map (+100) $ filter even $ [1..100]`. After monkey patching irunner.js and adding `console.log` I saw all the logs almost at the end, so it's a compiler issue? Or could it be that reading/writing stdin/stdout causes that?
- Whole approach of using [socket.io/node/irunner.js](https://github.com/ghcjs/ghcjs/blob/7aa7bae05b306bdb8f7a9c6e292ce74736e4541d/src/Compiler/InteractiveUI.hs#L473-L488). Can't we just open the socket from the Haskell? We have to serve index.html + client.js as well, but is there any requirements of using node?
- Nice to have - REPL to mobile environment like React Native. Mobile is a king nowadays, and as RN environments supports WebSocket from the box which means we need to change only client side

This projects shows the full potential of ghcjs https://github.com/jyrimatti/hseverywhere

I'm coming from ClojureScript environment where REPL works about in the same way, but it's stable and fast, so it's doable. I would be happy to contribute, but it would help a lot if you can guide me a bit.

Thank you

**Comment by artemyarulin** [comment]
Status update: I've create a proof of concept for the REPL to ReactNative environment https://github.com/artemyarulin/ghcjs-repl-react-native

Like I though just a few changes in the client js file were needed. Although I've noticed that even some simple expressions like `2` generates like 50k lines to evaluate in JS environment. Could it be the reason why it's so slow?

**Comment by luite** [comment]
The REPL loads the code incrementally. Typically the first few expressions will pull in a lot of dependencies. After that it's much faster.

I'm now updating the GHCJSi code to use the new external interpreter infrastructure in GHC 8 (which is based on the GHCJS Template Haskell runner. GHCJSi was a bit of a hack, and this makes the code a lot cleaner, hopefully more reliable too)

**Comment by luite** [comment]
Restarting the browser breaks the session in the current implementation, since the compiler doesn't keep track of disconnects and reconnects. For node.js that's not really a problem, since you'd usually not touch that process directly (but it would still be useful to recover a crashed connection).

The main reason that things break is that after a reconnect the GHCJS linker state is inconsistent with the browser: GHCJS thinks that some code is already there, while in reality the browser is starting with a blank slate, without even the basic RTS code.

What do you think should happen in case of a reconnect? It may be possible to restore some bindings, but if the user has done something like "myValue <- readFile ..." then just replaying the session would not necessarily result in the same values being there. And it would get more complicated if the user has started some threads, killed them again after some time. Should we just clear all the bindings?

I think 30 seconds is far too long by the way, for the expression you mentioned, and I haven't seen this on my own system. I have seen that Safari will somehow pause the JS runtime when the page is loaded in a background window or tab. Is it still this slow if the page is in the foreground, in focus?

**Comment by artemyarulin** [comment]
Hi, thank you for your response. 
I guess clean all is an only way to go, otherwise consistency would be at risk, you right.
Yep, I was using Safari, not sure if it was on top, maybe not.

👍 for updating it for GHC8, but for now I jumped to PureScript and I guess we can close it and hope that new version would be better. 

Thank you once again for all the explanation
