### ISSUE TITLE
h$__hsunix_lstat is not defined?

### ISSUE THREAD

**Issue by lierdakil** [ghcjs/ghcjs#531]
So, for reasons I don't really want to get into, I wanted to get myself a nodejs version of [hasktags](https://hackage.haskell.org/package/hasktags/) executable. It builds fine, and does output help messages. However, if I try to run it to do actual work, it crashes with

```
ReferenceError: h$__hsunix_lstat is not defined
    at NKb (/tmp/hasktags.js:1476:65)
    at Ge (/tmp/hasktags.js:164:452)
    at /tmp/hasktags.js:169:442
    at yc (/tmp/hasktags.js:130:287)
    at /tmp/hasktags.js:332:256
    at FSReqWrap.oncomplete (fs.js:82:15)
```

Any way to fix this at this moment?

**Comment by lierdakil** [comment]
ETIMEDOUT, closing.

**Comment by hamishmack** [comment]
Sorry, missed this somehow.

One fix for this would be to add shims to replace the C functions in the `unix` package (at least the ones that are used by hasktags).   C function in question is `__hsunix_lstat` in [HsUnix.c](https://hackage.haskell.org/package/unix-2.5.0.0/src/cbits/HsUnix.c).

This is complicated somewhat because the shim will need to use interruptable JS FFI (because node lstat is nonblocking). 

A similar function exists in the base package and the shim for that one is [here](https://github.com/ghcjs/shims/blob/0a6234261b4b13103ad8be898b93705bcf5dc3ae/pkg/base.js#L136).  This [patch](https://github.com/ghcjs/ghcjs-boot/blob/ghc-8.0/patches/base.patch#L655) replaces the C FFI with a JS FFI.

Perhaps a simpler fix might be to see if the `hasktags` package can be updated so that it does not depend on the `unix` package.

**Comment by lierdakil** [comment]
Thanks for the detailed answer! No worries, I did eventually figure out a workaround.

> Perhaps a simpler fix might be to see if the hasktags package can be updated so that it does not depend on the unix package.

Yes, that's exactly what I did back then. Dependency is rather superficial really. Never got around to contributing it upstream though, so maybe I'll do that.

All in all, this is really fine to close, and I don't want it haunting the backlog forever either. Hope you don't mind me re-closing after you just re-opened.
