### ISSUE TITLE
GHCJS 8.4 does not install all the same core packages as GHC

### ISSUE THREAD

**Issue by ElvishJerricco** [ghcjs/ghcjs#676]
- `ghc-compact`
- `haskeline`
- `hpc`
- `stm`
- `terminfo`
- `xhtml`

I'm sure that some of these are intentional. But I would expect e.g. `stm` and `ghc-compact` to come with GHCJS.

**Comment by luite** [comment]
I think `terminfo` was left out because of the `libterminfo` dependency. `stm` is a recent addition (it didn't come with GHC 8.2). It's still installable as a regular package.

Earlier GHCJS built lots of things (like `aeson`) with `ghcjs-boot`, which caused problems for packaging, since it was unnecessarily pinning versions of packages.

Is having _fewer_ packages than GHC in the global package db similarly problematic? If so, I think we should just add these packages to the boot package set.

**Comment by hvr** [comment]
Fwiw, I for one appreciate GHCJS's boot-set being minimal; I don't see any reason why `stm` or `xhtml` should be bundled with GHCJS; GHC only bundles those in the global pkg db because we were forced to; but those reasons that applied to GHC don't apply to GHCJS, so there's no need for GHCJS to bundle those extra libs, and nor should it.

**Comment by ElvishJerricco** [comment]
@hvr Yea I've come around to this. At first I didn't know whether it was technically a problem, and it required special attention in nixpkgs. But it seems better this way. Gonna close.

**Comment by Ericson2314** [comment]
@ElvishJerricco https://github.com/nixos/nixpkgs/blob/79362be2832b9ed1db72ae057305afb89960b950/pkgs/development/haskell-modules/configuration-ghcjs.nix#L28 no longer works in nixpkgs, as the last hackage bump removed that version of stm. I agree that pinned base packages are an abomination, and it's better to unpin, so can we just do that?

CC @luigy

**Comment by ryantrinkle** [comment]
We want the ghc and ghcjs package sets to agree as closely as possible,
because otherwise issues localized to only one or the other are more
likely. Would this impact that goal?

**Comment by ElvishJerricco** [comment]
@Ericson2314 can we just do what?

**Comment by Ericson2314** [comment]
@elvishjerricco Remove that pin—i take it from this thread that it is not needed technically.

@ryantrinkle agree, but I rather not do that by conflating hard GHCJS requirements with that goal. When we build all libraries separately it will be easy to automatically do this while keeping the "wants" and "needs" separate.

**Comment by Ericson2314** [comment]
Cherry-picked nixpkgs master https://github.com/nixos/nixpkgs/commit/bb78d6690606473757f9c2ce4dbf1e19569f03d2 for now to get around an eval failure, as at least a temp solution.

**Comment by ryantrinkle** [comment]
@Ericson2314 I'm not quite following - what's the "hard GHCJS requirement" in question here?  I don't think I have the full context yet.

**Comment by luigy** [comment]
for consistency in order to get the missing pkgs bundled it would also need to be listed here https://github.com/ghcjs/ghcjs/blob/ghc-8.4/lib/boot/boot.yaml#L36

**Comment by Ericson2314** [comment]
By "hard" I mean packages that must be forced to a specific version because GHCJS is deeply tied to them (via shims or whatever) else building will fail. That is opposed to pinning packages just for consistency, which the compilers themselves do not require.

Per what luigy said above, it looks like GHCJS pins packages that GHC doesn't, too, so just adding constraints for GHCJS isn't sufficient anyways. But if we make a separate overlay which can applied to both GHC and GHCJS package sets, we get true consistency, separation of concerns, and no redundancy.
