### ISSUE TITLE
GHCJS 8.4: ReferenceError: h$putenv is not defined

### ISSUE THREAD

**Issue by ElvishJerricco** [ghcjs/ghcjs#677]
I'm getting this error in the test suite of `hspec-core`. Full log: https://gist.github.com/ElvishJerricco/e6c4e18c45dfe30f0574f2fa6bfb068e

**Comment by luite** [comment]
ah an implementation is missing, I'll add it to the shims

another problem from the logs, I suspect there's something wrong with the cabal file for the base package:
```
Declaration for getCPUTime1
Unfolding of getCPUTime1:
  Failed to load interface for ‘System.CPUTime.Unsupported’
  Perhaps you haven't installed the "js_p" libraries for package ‘base-4.11.1.0’?
  Use -v to see a list of the files searched for.
```

**Comment by luite** [comment]
I found the problem with the base package cabal file (the `System.CPUTime.Unsupported` module was unlisted) and have an implementation of the missing environment functions.

`putenv` is a bit hard to implement exactly according to spec, which requires that the `char *` argument is actually made part of the environment. Changes to the string value later should be reflected in the environment. My implementation just copies the value, so that behaviour is lost (older glibc did the same)

I'll push after a bit more testing.

There are some more unimplemented things when running the `hspec-core` test suite. I'll see if it's reasonably doable to add the required operations (it's duplicating file descriptors, which is not directly supported by node.js)

**Comment by luite** [comment]
```
Finished in 2.8590 seconds
246 examples, 18 failures
```

got fd duplication to read back stdout working (it's using the `silently` package for that) and the whole testsuite runs now.

I'm still looking into the remaining test failures. one is related to environment variables.

**Comment by luite** [comment]
Almost done now:

```
  test/Test/Hspec/Core/QuickCheckUtilSpec.hs:97: 
  1) Test.Hspec.Core.QuickCheckUtil.parseQuickCheckResult, with NoExpectedFailure, includes verbose output
       expected: QuickCheckResult {quickCheckResultNumTests = 2, quickCheckResultInfo = "Passed:\n0\n\nPassed:\n-39", quickCheckResultStatus = QuickCheckOtherFailure "Passed 2 tests (expected failure)."}
        but got: QuickCheckResult {quickCheckResultNumTests = 2, quickCheckResultInfo = "Passed:\n0\n\nPassed:\n-19", quickCheckResultStatus = QuickCheckOtherFailure "Passed 2 tests (expected failure)."}

  test/Test/Hspec/Core/QuickCheckUtilSpec.hs:118: 
  2) Test.Hspec.Core.QuickCheckUtil.parseQuickCheckResult, with InsufficientCoverage, includes verbose output
       expected: QuickCheckResult {quickCheckResultNumTests = 2, quickCheckResultInfo = "Passed:\n0\n\nPassed:\n-39", quickCheckResultStatus = QuickCheckOtherFailure "Insufficient coverage after 2 tests (only 0% is 23, not 10%)."}
        but got: QuickCheckResult {quickCheckResultNumTests = 2, quickCheckResultInfo = "Passed:\n0\n\nPassed:\n-19", quickCheckResultStatus = QuickCheckOtherFailure "Insufficient coverage after 2 tests (only 0% is 23, not 10%)."}

Randomized with seed 2139052218

Finished in 2.9980 seconds
246 examples, 2 failures
```

this is after removing the conditional code from `Test.Hspec.Core.FailureReport` that works around GHCJS not supporting setting environment variables.

besides adding `putenv` (and `setenv` etc) support, and support for `hDuplicate`, I had to fix a few bugs to get there. I hope I can fix the last two failures tomorrow.

**Comment by luite** [comment]
added support with e1ee138bf77e959a77b5cb710e43337f566dfa3f
